### ISSUE TITLE
Connection closed by peer 

### ISSUE THREAD

**Issue by dokooh** [luca-medeiros/lightning-sam#43]
Hi, 

Thanks for your nice work so far. 

I tried to run your code on a SageMaker studio VM and I run into the following issue:

> (lightningsam) root@pytorch-2-0-0-gpu-py31-ml-m5-large-688742f28ae6243c9f9ea2d80bc2:~/lightning-sam# python lightning_sam/train.py 
> Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
> Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
> Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
> Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
> [rank: 3] Global seed set to 1340
> ----------------------------------------------------------------------------------------------------
> distributed_backend=gloo
> All distributed processes registered. Starting with 4 processes
> ----------------------------------------------------------------------------------------------------
> 
> [rank: 1] Global seed set to 1338
> [rank: 0] Global seed set to 1337
> [rank: 2] Global seed set to 1339
> loading annotations into memory...
> Done (t=0.01s)
> creating index...
> index created!
> loading annotations into memory...
> Done (t=0.00s)
> creating index...
> index created!
> /opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
>   warnings.warn(_create_warning_msg(
> Traceback (most recent call last):
>   File "/root/lightning-sam/lightning_sam/train.py", line 167, in <module>
>     main(cfg)
>   File "/root/lightning-sam/lightning_sam/train.py", line 160, in main
>     model, optimizer = fabric.setup(model, optimizer)
>   File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 204, in setup
>     module, optimizers = self._strategy.setup_module_and_optimizers(  # type: ignore[assignment]
>   File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/strategies/strategy.py", line 123, in setup_module_and_optimizers
>     module = self.setup_module(module)
>   File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/strategies/ddp.py", line 118, in setup_module
>     return DistributedDataParallel(module=module, device_ids=self._determine_ddp_device_ids(), **self._ddp_kwargs)
>   File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
>     _verify_param_shape_across_processes(self.process_group, parameters)
>   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
>     return dist._verify_params_across_processes(process_group, tensors, logger)
> RuntimeError: [/opt/conda/conda-bld/pytorch_1679586020379/work/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [169.255.255.2]:946

**Comment by dokooh** [comment]
I searched and it seems to be an open issue in pytorch: [](https://github.com/pytorch/pytorch/issues/75512)

Have replied to the thread, to see what they say, any way around you can foresee? Perhaps if I try to finetune on a local machine for example?

**Comment by dokooh** [comment]
I tried running the code on my local machine and I didn't manage to reproduce the issue, as such I am closing this issue.
