### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by choasup** [luca-medeiros/lightning-sam#5]
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/usr/local/python/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/python/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/python/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-t_cob8lk/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 41, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
        File "/tmp/pip-build-env-t_cob8lk/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 59, in __init__
          super().__init__(poetry, executable=executable)
        File "/tmp/pip-build-env-t_cob8lk/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/builder.py", line 83, in __init__
          self._module = Module(
        File "/tmp/pip-build-env-t_cob8lk/overlay/lib/python3.8/site-packages/poetry/core/masonry/utils/module.py", line 69, in __init__
          raise ModuleOrPackageNotFound(
      poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package lightning-sam
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Thanks for the repo, I wonder that how can I fix the problem?**

**Comment by luca-medeiros** [comment]
Hey @choasup 

Had some issues with the pyproject. I think it got fixed here #7 
Mind trying it again after a git pull?

**Comment by Ashutosh1995** [comment]
@luca-medeiros getting same issue, kindly help out!

**Comment by ChunmengLiu1** [comment]
> @luca-medeiros getting same issue, kindly help out!

Hi, I met the same problem. Did you solve it? Thanks!

**Comment by citystrawman** [comment]
> Hey @choasup
> 
> Had some issues with the pyproject. I think it got fixed here #7 Mind trying it again after a git pull?

I just encountered a similar problem: 
```
(LightningSAM) PS D:\programs\lightning-sam> pip install .
DEPRECATION: Loading egg at c:\users\cngim\anaconda3\lib\site-packages\mask_rcnn-2.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing d:\programs\lightning-sam
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\CNGIM\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\CNGIM\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\CNGIM\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\CNGIM\AppData\Local\Temp\pip-build-env-ot4l8xqn\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 42, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\CNGIM\AppData\Local\Temp\pip-build-env-ot4l8xqn\overlay\Lib\site-packages\poetry\core\factory.py", line 60, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - data.documentation must be uri

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I am not sure if this is solved yet, or is it a new problem?

**Comment by luca-medeiros** [comment]
@citystrawman Yea, its a different issue.
```
...
      RuntimeError: The Poetry configuration is invalid:
        - data.documentation must be uri
        
     
```
Newer versions of poetry require https://github.com/luca-medeiros/lightning-sam/blob/b43d79ea47fd5e8bfe34d961e0ad68fc079b2e52/pyproject.toml#L6 this to be a link. Accepting PRs for the fix.

**Comment by ZnS-oscar** [comment]
> @citystrawman Yea, its a different issue.
> 
> ```
> ...
>       RuntimeError: The Poetry configuration is invalid:
>         - data.documentation must be uri
>         
>      
> ```
> 
> Newer versions of poetry require
> 
> https://github.com/luca-medeiros/lightning-sam/blob/b43d79ea47fd5e8bfe34d961e0ad68fc079b2e52/pyproject.toml#L6
> 
> this to be a link. Accepting PRs for the fix.

by deleting this line `documentation = "" ` seems to fix the error 
```
RuntimeError: The Poetry configuration is invalid:
        - data.documentation must be uri
```

**Comment by citystrawman** [comment]
> > @citystrawman Yea, its a different issue.
> > ```
> > ...
> >       RuntimeError: The Poetry configuration is invalid:
> >         - data.documentation must be uri
> >         
> >      
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Newer versions of poetry require
> > https://github.com/luca-medeiros/lightning-sam/blob/b43d79ea47fd5e8bfe34d961e0ad68fc079b2e52/pyproject.toml#L6
> > 
> > this to be a link. Accepting PRs for the fix.
> 
> by deleting this line `documentation = "" ` seems to fix the error
> 
> ```
> RuntimeError: The Poetry configuration is invalid:
>         - data.documentation must be uri
> ```

Thank you. I'll try it later :)
